### ISSUE TITLE
Segmentation Fault ERROR

### ISSUE THREAD

**Issue by Amajo0209** [marcoslucianops/DeepStream-Yolo-Face#3]
Hello.
I am trying to run the Python file from this repository using the given command: python3 deepstream.py -s file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4 -c config_infer_primary_yoloV8_face.txt

Every time I run the command I'm getting Segmentation fault ERROR with a black screen, below is the log I get while running the file:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ubuntu@ubuntu-Blade-15-2022-RZ09-0421:~/Documents/DeepStream-Yolo-Face$ python3 deepstream.py -s file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4 -c config_infer_primary_yoloV8_face.txt

SOURCE: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
CONFIG_INFER: config_infer_primary_yoloV8_face.txt
STREAMMUX_BATCH_SIZE: 1
STREAMMUX_WIDTH: 1920
STREAMMUX_HEIGHT: 1080
GPU_ID: 0
PERF_MEASUREMENT_INTERVAL_SEC: 5
JETSON: FALSE

gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
[NvMultiObjectTracker] Initialized
0:00:03.122840037 24409      0x3042a60 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<pgie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1988> [UID = 1]: deserialized trt engine from :/home/ubuntu/Documents/DeepStream-Yolo-Face/yolov8n-face.onnx_b1_gpu0_fp32.engine
WARNING: [TRT]: The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT images          3x640x640       
1   OUTPUT kFLOAT output0         5x8400          

0:00:03.173926305 24409      0x3042a60 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<pgie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2091> [UID = 1]: Use deserialized engine model: /home/ubuntu/Documents/DeepStream-Yolo-Face/yolov8n-face.onnx_b1_gpu0_fp32.engine
0:00:03.175549029 24409      0x3042a60 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<pgie> [UID 1]: Load new model:config_infer_primary_yoloV8_face.txt sucessfully

Segmentation fault (core dumped)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Please, I wonder if anyone could help me with this issue, how can I fix it?

DeepStream Version = 6.3
YOLO MODEL = Yolov8n-face
CUDA = 12.3
TensorRT = 8.5.3.1
NVIDIA GRAPHIC = GeForce RTX 3080 Ti
32GB RAM and 1TB SSD

**Comment by Amajo0209** [comment]
I Just solved this is

**Comment by iamamiramine** [comment]
@Amajo0209  May I ask how did you solve it?

**Comment by marcoslucianops** [comment]
Please follow the steps in the docs folder.
